"""Add ingredients field to MealPlan

Revision ID: da6c6d107d65
Revises: 78e88d14a5d1
Create Date: 2025-07-08 17:19:24.832624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6c6d107d65'
down_revision = '78e88d14a5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
